"use strict";

const getCharacters = () => {
  return {
    "" : [
        {
          "name": "Harry",
          "hairType": "straight",
          "hairColor": "brown",
          "hairLength": "short",
          "definingFeature": null,
          "gender": "male",
          "accessory": "glasses",
          "age": "child",
          "species": "wizard",
          "role": "student",
          "house": "Griffindor",
          "id": 1,
          "facialHair": null
        },
        {
          "name": "Hermione",
          "hairType": "curly",
          "hairColor": "brown",
          "hairLength": "long",
          "definingFeature": null,
          "gender": "female",
          "accessory": null,
          "age": "child",
          "species": "wizard",
          "role": "student",
          "house": "Griffindor",
          "id": 2,
          "facialHair": null
        },
        {
          "name": "Ron",
          "hairType": "straight",
          "hairColor": "red",
          "hairLength": "short",
          "definingFeature": null,
          "gender": "male",
          "accessory": null,
          "age": "child",
          "species": "wizard",
          "role": "student",
          "house": "Griffindor",
          "id": 3,
          "facialHair": null
        },
        {
          "name": "Dumbledore",
          "hairType": "straight",
          "hairColor": "gray",
          "hairLength": "long",
          "definingFeature": null,
          "gender": "male",
          "accessory": null,
          "age": "old",
          "species": "wizard",
          "role": "staff",
          "house": "Griffindor",
          "id": 4,
          "facialHair": "beard"
        },
        {
          "name": "Snape",
          "hairType": "straight",
          "hairColor": "black",
          "hairLength": "medium",
          "definingFeature": null,
          "gender": "male",
          "accessory": null,
          "age": "adult",
          "species": "wizard",
          "role": "staff",
          "house": "Slytherin",
          "id": 5,
          "facialHair": null
        },
        {
          "name": "Neville",
          "hairType": "straight",
          "hairColor": "brown",
          "hairLength": "short",
          "definingFeature": null,
          "gender": "male",
          "accessory": null,
          "age": "child",
          "species": "wizard",
          "role": "student",
          "house": "Griffindor",
          "id": 6,
          "facialHair": null
        },
        {
          "name": "Draco",
          "hairType": "straight",
          "hairColor": "blonde",
          "hairLength": "short",
          "definingFeature": null,
          "gender": "male",
          "accessory": null,
          "age": "child",
          "species": "wizard",
          "role": "student",
          "house": "Slytherin",
          "id": 7,
          "facialHair": null
        },
        {
          "name": "Dobby",
          "hairType": null,
          "hairColor": null,
          "hairLength": "bald",
          "definingFeature": "ears",
          "gender": "male",
          "accessory": null,
          "age": "old",
          "species": "elf",
          "role": "servant",
          "house": null,
          "id": 8,
          "facialHair": null
        },
        {
          "name": "Voldemort",
          "hairType": null,
          "hairColor": null,
          "hairLength": "bald",
          "definingFeature": "nose",
          "gender": "male",
          "accessory": null,
          "age": "old",
          "species": "wizard",
          "role": null,
          "house": "Slytherin",
          "id": 9,
          "facialHair": null
        },
        {
          "name": "McGonagall",
          "hairType": "straight",
          "hairColor": "gray",
          "hairLength": "long",
          "definingFeature": null,
          "gender": "female",
          "accessory": "hat",
          "age": "old",
          "species": "wizard",
          "role": "staff",
          "house": "Griffindor",
          "id": 10,
          "facialHair": null
        },
        {
          "name": "Hagrid",
          "hairType": "curly",
          "hairColor": "brown",
          "hairLength": "long",
          "definingFeature": null,
          "gender": "male",
          "accessory": null,
          "age": "adult",
          "species": "wizard",
          "role": "staff",
          "house": "Griffindor",
          "id": 11,
          "facialHair": "beard"
        },
        {
          "name": "Sirius",
          "hairType": "curly",
          "hairColor": "black",
          "hairLength": "medium",
          "definingFeature": null,
          "gender": "male",
          "accessory": null,
          "age": "adult",
          "species": "wizard",
          "role": "staff",
          "house": "Griffindor",
          "id": 12,
          "facialHair": "beard"
        },
        {
          "name": "Filch",
          "hairType": "straight",
          "hairColor": "gray",
          "hairLength": "long",
          "definingFeature": null,
          "gender": "male",
          "accessory": null,
          "age": "old",
          "species": "squib",
          "role": "staff",
          "house": null,
          "id": 13,
          "facialHair": null
        },
        {
          "name": "Dudley",
          "hairType": "straight",
          "hairColor": "brown",
          "hairLength": "short",
          "definingFeature": null,
          "gender": "male",
          "accessory": null,
          "age": "child",
          "species": "muggle",
          "role": null,
          "house": null,
          "id": 14,
          "facialHair": null
        },
        {
          "name": "Luna",
          "hairType": "curly",
          "hairColor": "blonde",
          "hairLength": "long",
          "definingFeature": null,
          "gender": "female",
          "accessory": null,
          "age": "child",
          "species": "wizard",
          "role": "student",
          "house": "Ravenclaw",
          "id": 15,
          "facialHair": null
        },
        {
          "name": "Hedwig",
          "hairType": "feathers",
          "hairColor": null,
          "hairLength": null,
          "definingFeature": "beak",
          "gender": "other",
          "accessory": null,
          "age": null,
          "species": "animal",
          "role": "servant",
          "house": null,
          "id": 16,
          "facialHair": null
        },
        {
          "name": "Nagini",
          "hairType": null,
          "hairColor": null,
          "hairLength": null,
          "definingFeature": "nose",
          "gender": "other",
          "accessory": null,
          "age": null,
          "species": "animal",
          "role": "servant",
          "house": null,
          "id": 17,
          "facialHair": null
        },
        {
          "name": "Bellatrix",
          "hairType": "curly",
          "hairColor": "black",
          "hairLength": "long",
          "definingFeature": null,
          "gender": "female",
          "accessory": null,
          "age": "adult",
          "species": "wizard",
          "role": null,
          "house": "Slytherin",
          "id": 18,
          "facialHair": null
        },
        {
          "name": "Umbridge",
          "hairType": "curly",
          "hairColor": "brown",
          "hairLength": "short",
          "definingFeature": null,
          "gender": "female",
          "accessory": "hat",
          "age": "adult",
          "species": "wizard",
          "role": "staff",
          "house": "Slytherin",
          "id": 19,
          "facialHair": null
        },
        {
          "name": "Ginny",
          "hairType": "straight",
          "hairColor": "red",
          "hairLength": "long",
          "definingFeature": null,
          "gender": "female",
          "accessory": null,
          "age": "child",
          "species": "wizard",
          "role": "student",
          "house": "Griffindor",
          "id": 20,
          "facialHair": null
        },
        {
          "name": "Lupin",
          "hairType": "straight",
          "hairColor": "red",
          "hairLength": "short",
          "definingFeature": null,
          "gender": "male",
          "accessory": null,
          "age": "adult",
          "species": "wizard",
          "role": "staff",
          "house": "Griffindor",
          "id": 21,
          "facialHair": "mustache"
        },
        {
          "name": "Trelawney",
          "hairType": "curly",
          "hairColor": "brown",
          "hairLength": "long",
          "definingFeature": null,
          "gender": "female",
          "accessory": "glasses",
          "age": "adult",
          "species": "wizard",
          "role": "staff",
          "house": "Ravenclaw",
          "id": 22,
          "facialHair": null
        },
        {
          "name": "Myrtle",
          "hairType": "straight",
          "hairColor": "brown",
          "hairLength": "long",
          "definingFeature": null,
          "gender": "female",
          "accessory": "glasses",
          "age": "child",
          "species": "wizard",
          "role": "student",
          "house": "Ravenclaw",
          "id": 23,
          "facialHair": null
        },
        {
          "name": "Moody",
          "hairType": "straight",
          "hairColor": "blonde",
          "hairLength": "medium",
          "definingFeature": "eye",
          "gender": "male",
          "accessory": null,
          "age": "adult",
          "species": "wizard",
          "role": "staff",
          "house": null,
          "id": 24,
          "facialHair": null
        }
       ]
}
}

module.exports = {
  getCharacters
}